---
on:
  pull_request:

jobs:
  markdownlint:
    uses: Stromweld/github-workflows/.github/workflows/markdownlint.yml@main
  yamllint:
    uses: Stromweld/github-workflows/.github/workflows/yamllint.yml@main
#  markdownlint:
#    runs-on: ubuntu-latest
#    container: ruby:alpine
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@main
#      - name: Run Markdown Lint
#        run: |
#          gem install mdl
#          find . -not -path "*/\.*" -type f -iname "*.md" -exec mdl \{\} \+
#  yamllint:
#    runs-on: ubuntu-latest
#    container: ruby:alpine
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@main
#      - name: Run Yaml Linter
#        run: |
#          gem install yaml-lint
#          yaml-lint -i ./

  check:
    if: always()

    needs:
      - markdownlint
      - yamllint

    runs-on: Ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures:
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
