---
on:
  pull_request:

jobs:
  markdown-lint:
    uses: Stromweld/github-workflows/.github/workflows/markdown-lint.yml@main

  markdown-link-checker:
    uses: Stromweld/github-workflows/.github/workflows/markdown-link-checker.yml@main

  yaml-lint:
    uses: Stromweld/github-workflows/.github/workflows/yaml-lint.yml@main

  check:
    if: always()
    needs:
      - markdown-lint
      - markdown-link-checker
      - yaml-lint
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures:
            - markdown-link-checker
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
