---
on:
  workflow_call:
    inputs:
      SUPERMARKET_URL:
        required: true
        type: string
      SUPERMARKET_USER:
        required: true
        type: string
    secrets:
      SUPERMARKET_KEY:
        required: true

jobs:
  supermarket-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Upload to Supermarket
        run: |
          echo "${{ secrets.SUPERMARKET_KEY }}" >> ~/super.pem
          knife supermarket share $(grep -oP "(?<=name ')[^' ]+" ./metadata.rb) -u $SUPERMARKET_USER -k ~/super.pem -o ../ -m $SUPERMARKET_URL
        env:
          CHEF_LICENSE: accept-no-persist
          SUPERMARKET_URL: ${{ inputs.SUPERMARKET_URL }}
          SUPERMARKET_USER: ${{ inputs.SUPERMARKET_USER }}
