---
on:
  workflow_call:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    container: ruby:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@main
        id: verify-changed-files
        with:
          files: |
            **.md
      - name: Run Markdown Linter
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          gem install mdl
          find . -not -path "*/\.*" -type f -iname "*.md" -exec mdl \{\} \+
