---
on:
  workflow_call:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    container: python:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@main
        id: verify-changed-files
        with:
          files: |
            **/**.py
      - name: Run Python Lint
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          pip install --no-cache-dir boto boto3 pylint
          find . -not -path "*/\.*" -type f -iname "*.py" -exec pylint \{\} \+
