---
on:
  workflow_call:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    container: ruby:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Pull Change list
        id: changed-files
        uses: collin-miller/git-changesets@master
      - name: Verify Changed files
        id: verify-changed-files
        run: |
          changed=${{ steps.changed-files.outputs.added_modified }}
          if grep ".*\.yml|.*\.yaml" <<< $changed; then
            echo "::set-output name=files_changed::'true'"
          else
            echo "::set-output name=files_changed::'false'"
          fi
          echo $changed
      - name: Run Yaml Linter
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          gem install yaml-lint
          yaml-lint -i ./
