---
on:
  workflow_call:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    container: ruby:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      id: verify-changed-files
        run: |
          if git diff --diff-filter=d --name-only main main^@ | grep ".*\.yml|.*\.yaml"; then
            echo "::set-output name=files_changed::'true'"
          else
            echo "::set-output name=files_changed::'false'"
          fi
      - name: Run Yaml Linter
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          gem install yaml-lint
          yaml-lint -i ./
