---
on:
  workflow_call:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    container: ruby:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Verify Changed files
        id: verify-changed-files
        run: |
          apk add --no-cache git
          changed=`git diff --diff-filter=d --name-only --merge-base`
          if grep ".*\.yml|.*\.yaml" <<< $changed; then
            echo "::set-output name=files_changed::'true'"
          else
            echo "::set-output name=files_changed::'false'"
          fi
          echo $changed
      - name: Run Yaml Linter
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          gem install yaml-lint
          yaml-lint -i ./
